version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mpa
    volumes:
      - /var/lib/postgresql/data

  server:
    image: mpa-server
    build:
      .
    links:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=jdbc:postgresql://db:5432/mpa
      - DB_USER=postgres
      - DB_PASSWORD=password
